### ISSUE TITLE
get_if_hwaddr("eth0") returns MAC address of eth0 outside run environment

### ISSUE THREAD

**Issue by hidehiroanto** [pwncollege/intro-to-cybersecurity-dojo#17]
The scapy.get_if_hwaddr("eth0") call [here](https://github.com/pwncollege/intro-to-cybersecurity-dojo/blob/main/intercepting-communication/run#L207) always returns the MAC address of the eth0 interface outside of the run environment. This breaks Level 12 of Intercepting Communication.

Moving it below the scapy.conf.ifaces.reload() line fixes it.

**Comment by ConnorNelson** [comment]
Thanks!
