### ISSUE TITLE
Minor typo in presentation Web Security 4: Same-Origin Policy

### ISSUE THREAD

**Issue by markrouz** [pwncollege/intro-to-cybersecurity-dojo#27]
https://docs.google.com/presentation/d/1KkiR8B_9xQilW_yq6W9FZ6xBN78V0S1aH1XvQfufYIk/edit#slide=id.g174c73f9fff_0_221

"In unspecified" should be "If unspecified"

**Comment by ConnorNelson** [comment]
Fixed it, thanks!
